# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nvidia/ai4m/audio/v1/audio.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'nvidia/ai4m/audio/v1/audio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n nvidia/ai4m/audio/v1/audio.proto\x12\x14nvidia.ai4m.audio.v1\"\xb0\x01\n\x0b\x41udioConfig\x12\x32\n\x08\x65ncoding\x18\x01 \x01(\x0e\x32 .nvidia.ai4m.audio.v1.AudioCodec\x12\x36\n\x06\x66ormat\x18\x02 \x01(\x0e\x32!.nvidia.ai4m.audio.v1.AudioFormatH\x00\x88\x01\x01\x12\x19\n\x0c\x62itrate_kbps\x18\x03 \x01(\rH\x01\x88\x01\x01\x42\t\n\x07_formatB\x0f\n\r_bitrate_kbps\"%\n\rAudioEncoding\x12\x14\n\x0c\x62itrate_kbps\x18\x01 \x01(\r*i\n\nAudioCodec\x12\x1b\n\x17\x41UDIO_CODEC_UNSPECIFIED\x10\x00\x12\x13\n\x0f\x41UDIO_CODEC_MP3\x10\x01\x12\x13\n\x0f\x41UDIO_CODEC_WAV\x10\x02\x12\x14\n\x10\x41UDIO_CODEC_OPUS\x10\x03*C\n\x0b\x41udioFormat\x12\x1c\n\x18\x41UDIO_FORMAT_UNSPECIFIED\x10\x00\x12\x16\n\x12\x41UDIO_FORMAT_S16LE\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nvidia.ai4m.audio.v1.audio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCODEC']._serialized_start=276
  _globals['_AUDIOCODEC']._serialized_end=381
  _globals['_AUDIOFORMAT']._serialized_start=383
  _globals['_AUDIOFORMAT']._serialized_end=450
  _globals['_AUDIOCONFIG']._serialized_start=59
  _globals['_AUDIOCONFIG']._serialized_end=235
  _globals['_AUDIOENCODING']._serialized_start=237
  _globals['_AUDIOENCODING']._serialized_end=274
# @@protoc_insertion_point(module_scope)
