# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nvidia/ai4m/video/v1/video.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'nvidia/ai4m/video/v1/video.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n nvidia/ai4m/video/v1/video.proto\x12\x14nvidia.ai4m.video.v1\x1a\x19google/protobuf/any.proto\"\x84\x01\n\x0bVideoConfig\x12\x35\n\x08\x65ncoding\x18\x01 \x01(\x0b\x32#.nvidia.ai4m.video.v1.VideoEncoding\x12\x34\n\x05\x63odec\x18\x02 \x01(\x0e\x32 .nvidia.ai4m.video.v1.VideoCodecH\x00\x88\x01\x01\x42\x08\n\x06_codec\"g\n\rLossyEncoding\x12\x19\n\x0c\x62itrate_mbps\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x19\n\x0cidr_interval\x18\x02 \x01(\rH\x01\x88\x01\x01\x42\x0f\n\r_bitrate_mbpsB\x0f\n\r_idr_interval\"\xa3\x01\n\x14\x43ustomEncodingParams\x12\x46\n\x06\x63ustom\x18\x01 \x03(\x0b\x32\x36.nvidia.ai4m.video.v1.CustomEncodingParams.CustomEntry\x1a\x43\n\x0b\x43ustomEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any:\x02\x38\x01\"\xb1\x01\n\rVideoEncoding\x12\x12\n\x08lossless\x18\x01 \x01(\x08H\x00\x12\x34\n\x05lossy\x18\x02 \x01(\x0b\x32#.nvidia.ai4m.video.v1.LossyEncodingH\x00\x12\x45\n\x0f\x63ustom_encoding\x18\x03 \x01(\x0b\x32*.nvidia.ai4m.video.v1.CustomEncodingParamsH\x00\x42\x0f\n\rencoding_type*?\n\nVideoCodec\x12\x1b\n\x17VIDEO_CODEC_UNSPECIFIED\x10\x00\x12\x14\n\x10VIDEO_CODEC_H264\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nvidia.ai4m.video.v1.video_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CUSTOMENCODINGPARAMS_CUSTOMENTRY']._loaded_options = None
  _globals['_CUSTOMENCODINGPARAMS_CUSTOMENTRY']._serialized_options = b'8\001'
  _globals['_VIDEOCODEC']._serialized_start=671
  _globals['_VIDEOCODEC']._serialized_end=734
  _globals['_VIDEOCONFIG']._serialized_start=86
  _globals['_VIDEOCONFIG']._serialized_end=218
  _globals['_LOSSYENCODING']._serialized_start=220
  _globals['_LOSSYENCODING']._serialized_end=323
  _globals['_CUSTOMENCODINGPARAMS']._serialized_start=326
  _globals['_CUSTOMENCODINGPARAMS']._serialized_end=489
  _globals['_CUSTOMENCODINGPARAMS_CUSTOMENTRY']._serialized_start=422
  _globals['_CUSTOMENCODINGPARAMS_CUSTOMENTRY']._serialized_end=489
  _globals['_VIDEOENCODING']._serialized_start=492
  _globals['_VIDEOENCODING']._serialized_end=669
# @@protoc_insertion_point(module_scope)
