# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: syntheticvideodetector.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'syntheticvideodetector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1csyntheticvideodetector.proto\x12\'nvidia.maxine.syntheticvideodetector.v1\x1a\x1bgoogle/protobuf/empty.proto\"6\n\x1b\x44\x65tectSyntheticVideoRequest\x12\x17\n\x0fvideo_file_data\x18\x01 \x01(\x0c\"\xf6\x01\n\x1c\x44\x65tectSyntheticVideoResponse\x12J\n\x0b\x63lip_result\x18\x01 \x01(\x0b\x32\x33.nvidia.maxine.syntheticvideodetector.v1.ClipResultH\x00\x12L\n\x0c\x66inal_result\x18\x02 \x01(\x0b\x32\x34.nvidia.maxine.syntheticvideodetector.v1.VideoResultH\x00\x12+\n\tkeepalive\x18\x03 \x01(\x0b\x32\x16.google.protobuf.EmptyH\x00\x42\x0f\n\rstream_output\"*\n\nClipResult\x12\r\n\x05index\x18\x01 \x01(\r\x12\r\n\x05logit\x18\x02 \x01(\x02\"X\n\x0bVideoResult\x12\r\n\x05logit\x18\x01 \x01(\x02\x12\x13\n\x0bprobability\x18\x02 \x01(\x02\x12\x10\n\x08\x63sv_data\x18\x03 \x01(\t\x12\x13\n\x0btotal_clips\x18\x04 \x01(\r2\xcb\x01\n\x1dSyntheticVideoDetectorService\x12\xa9\x01\n\x14\x44\x65tectSyntheticVideo\x12\x44.nvidia.maxine.syntheticvideodetector.v1.DetectSyntheticVideoRequest\x1a\x45.nvidia.maxine.syntheticvideodetector.v1.DetectSyntheticVideoResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'syntheticvideodetector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DETECTSYNTHETICVIDEOREQUEST']._serialized_start=102
  _globals['_DETECTSYNTHETICVIDEOREQUEST']._serialized_end=156
  _globals['_DETECTSYNTHETICVIDEORESPONSE']._serialized_start=159
  _globals['_DETECTSYNTHETICVIDEORESPONSE']._serialized_end=405
  _globals['_CLIPRESULT']._serialized_start=407
  _globals['_CLIPRESULT']._serialized_end=449
  _globals['_VIDEORESULT']._serialized_start=451
  _globals['_VIDEORESULT']._serialized_end=539
  _globals['_SYNTHETICVIDEODETECTORSERVICE']._serialized_start=542
  _globals['_SYNTHETICVIDEODETECTORSERVICE']._serialized_end=745
# @@protoc_insertion_point(module_scope)
