# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from nvidia.ai4m.lipsync.v1 import lipsync_pb2 as nvidia_dot_ai4m_dot_lipsync_dot_v1_dot_lipsync__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in nvidia/ai4m/lipsync/v1/lipsync_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LipSyncServiceStub(object):
    """LipSyncService provides APIs for lip sync animation

    The service takes input video and audio files and generates an output video
    with synchronized lip movements matching the audio.

    The Lipsync API supports both transactional and streaming processing
    through gRPC.

    The service supports:
    Extending audio with silence when video is longer (only for transactional)
    Looping video when audio is longer (only for transactional)
    Configurable output video encoding

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Lipsync = channel.stream_stream(
                '/nvidia.ai4m.lipsync.v1.LipSyncService/Lipsync',
                request_serializer=nvidia_dot_ai4m_dot_lipsync_dot_v1_dot_lipsync__pb2.LipsyncRequest.SerializeToString,
                response_deserializer=nvidia_dot_ai4m_dot_lipsync_dot_v1_dot_lipsync__pb2.LipsyncResponse.FromString,
                _registered_method=True)


class LipSyncServiceServicer(object):
    """LipSyncService provides APIs for lip sync animation

    The service takes input video and audio files and generates an output video
    with synchronized lip movements matching the audio.

    The Lipsync API supports both transactional and streaming processing
    through gRPC.

    The service supports:
    Extending audio with silence when video is longer (only for transactional)
    Looping video when audio is longer (only for transactional)
    Configurable output video encoding

    """

    def Lipsync(self, request_iterator, context):
        """Lipsync is a bidirectional streaming RPC that takes video and audio
        input and returns a lip synchronized video output.
        request: Stream of LipsyncRequest messages containing
        either configuration or input data
        response: Stream of LipsyncResponse messages containing either
        configuration, video data, or keepalive
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LipSyncServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Lipsync': grpc.stream_stream_rpc_method_handler(
                    servicer.Lipsync,
                    request_deserializer=nvidia_dot_ai4m_dot_lipsync_dot_v1_dot_lipsync__pb2.LipsyncRequest.FromString,
                    response_serializer=nvidia_dot_ai4m_dot_lipsync_dot_v1_dot_lipsync__pb2.LipsyncResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nvidia.ai4m.lipsync.v1.LipSyncService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nvidia.ai4m.lipsync.v1.LipSyncService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LipSyncService(object):
    """LipSyncService provides APIs for lip sync animation

    The service takes input video and audio files and generates an output video
    with synchronized lip movements matching the audio.

    The Lipsync API supports both transactional and streaming processing
    through gRPC.

    The service supports:
    Extending audio with silence when video is longer (only for transactional)
    Looping video when audio is longer (only for transactional)
    Configurable output video encoding

    """

    @staticmethod
    def Lipsync(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/nvidia.ai4m.lipsync.v1.LipSyncService/Lipsync',
            nvidia_dot_ai4m_dot_lipsync_dot_v1_dot_lipsync__pb2.LipsyncRequest.SerializeToString,
            nvidia_dot_ai4m_dot_lipsync_dot_v1_dot_lipsync__pb2.LipsyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
