# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from nvidia.ai4m.activespeakerdetection.v1 import activespeakerdetection_pb2 as nvidia_dot_ai4m_dot_activespeakerdetection_dot_v1_dot_activespeakerdetection__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in nvidia/ai4m/activespeakerdetection/v1/activespeakerdetection_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ActiveSpeakerDetectionServiceStub(object):
    """ActiveSpeakerDetectionService provides APIs for active speaker detection

    The service takes video, audio and diarization files as inputs
    and generates Region of Interest bounding box
    corresponding to the active speaker and returns it
    along with the speaker metadata for each frame.

    The DetectActiveSpeaker API supports both transactional
    and streaming processing through gRPC.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectActiveSpeaker = channel.stream_stream(
                '/nvidia.ai4m.activespeakerdetection.v1.ActiveSpeakerDetectionService/DetectActiveSpeaker',
                request_serializer=nvidia_dot_ai4m_dot_activespeakerdetection_dot_v1_dot_activespeakerdetection__pb2.DetectActiveSpeakerRequest.SerializeToString,
                response_deserializer=nvidia_dot_ai4m_dot_activespeakerdetection_dot_v1_dot_activespeakerdetection__pb2.DetectActiveSpeakerResponse.FromString,
                _registered_method=True)


class ActiveSpeakerDetectionServiceServicer(object):
    """ActiveSpeakerDetectionService provides APIs for active speaker detection

    The service takes video, audio and diarization files as inputs
    and generates Region of Interest bounding box
    corresponding to the active speaker and returns it
    along with the speaker metadata for each frame.

    The DetectActiveSpeaker API supports both transactional
    and streaming processing through gRPC.

    """

    def DetectActiveSpeaker(self, request_iterator, context):
        """DetectActiveSpeaker is a bidirectional streaming RPC that takes audio file,
        video file and diarization file as inputs and returns a bounding box
        corresponding to the active speaker and its speaker tag for each frame.
        request: Stream of DetectActiveSpeakerRequest messages containing
        either configuration or input data
        response: Stream of DetectActiveSpeakerResponse messages
        containing either configuration, bounding box
        and speaker tag for each frame, or keepalive
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActiveSpeakerDetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectActiveSpeaker': grpc.stream_stream_rpc_method_handler(
                    servicer.DetectActiveSpeaker,
                    request_deserializer=nvidia_dot_ai4m_dot_activespeakerdetection_dot_v1_dot_activespeakerdetection__pb2.DetectActiveSpeakerRequest.FromString,
                    response_serializer=nvidia_dot_ai4m_dot_activespeakerdetection_dot_v1_dot_activespeakerdetection__pb2.DetectActiveSpeakerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nvidia.ai4m.activespeakerdetection.v1.ActiveSpeakerDetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nvidia.ai4m.activespeakerdetection.v1.ActiveSpeakerDetectionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ActiveSpeakerDetectionService(object):
    """ActiveSpeakerDetectionService provides APIs for active speaker detection

    The service takes video, audio and diarization files as inputs
    and generates Region of Interest bounding box
    corresponding to the active speaker and returns it
    along with the speaker metadata for each frame.

    The DetectActiveSpeaker API supports both transactional
    and streaming processing through gRPC.

    """

    @staticmethod
    def DetectActiveSpeaker(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/nvidia.ai4m.activespeakerdetection.v1.ActiveSpeakerDetectionService/DetectActiveSpeaker',
            nvidia_dot_ai4m_dot_activespeakerdetection_dot_v1_dot_activespeakerdetection__pb2.DetectActiveSpeakerRequest.SerializeToString,
            nvidia_dot_ai4m_dot_activespeakerdetection_dot_v1_dot_activespeakerdetection__pb2.DetectActiveSpeakerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
