# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from nvidia.ai4m.relighting.v1 import relighting_pb2 as nvidia_dot_ai4m_dot_relighting_dot_v1_dot_relighting__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nvidia/ai4m/relighting/v1/relighting_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VideoRelightingServiceStub(object):
    """The VideoRelightingService provides APIs to run the
    AI for Media Relighting feature on video streams.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Relight = channel.stream_stream(
                '/nvidia.ai4m.relighting.v1.VideoRelightingService/Relight',
                request_serializer=nvidia_dot_ai4m_dot_relighting_dot_v1_dot_relighting__pb2.RelightRequest.SerializeToString,
                response_deserializer=nvidia_dot_ai4m_dot_relighting_dot_v1_dot_relighting__pb2.RelightResponse.FromString,
                _registered_method=True)


class VideoRelightingServiceServicer(object):
    """The VideoRelightingService provides APIs to run the
    AI for Media Relighting feature on video streams.
    """

    def Relight(self, request_iterator, context):
        """Relight is a bidirectional streaming API to run the
        AI for Media Relighting feature on video streams.

        Protocol:
        1. Client sends RelightConfig (optionally indicating inline image uploads)
        2. Client streams ImageData chunks (if configured)
        3. Server sends ImageUploadAck for each image after successful decode
        4. Client streams video data chunks
        5. Server streams back processed video data chunks

        Images (HDRI, background) are sent inline as ImageData within
        the same Relight stream.

        Config updates can be sent mid-stream to change parameters.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoRelightingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Relight': grpc.stream_stream_rpc_method_handler(
                    servicer.Relight,
                    request_deserializer=nvidia_dot_ai4m_dot_relighting_dot_v1_dot_relighting__pb2.RelightRequest.FromString,
                    response_serializer=nvidia_dot_ai4m_dot_relighting_dot_v1_dot_relighting__pb2.RelightResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nvidia.ai4m.relighting.v1.VideoRelightingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nvidia.ai4m.relighting.v1.VideoRelightingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VideoRelightingService(object):
    """The VideoRelightingService provides APIs to run the
    AI for Media Relighting feature on video streams.
    """

    @staticmethod
    def Relight(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/nvidia.ai4m.relighting.v1.VideoRelightingService/Relight',
            nvidia_dot_ai4m_dot_relighting_dot_v1_dot_relighting__pb2.RelightRequest.SerializeToString,
            nvidia_dot_ai4m_dot_relighting_dot_v1_dot_relighting__pb2.RelightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
